# DISABLED: Uncomment when server is ready
# name: Deploy to Production Server
# 
# on:
#   push:
#     branches:
#       - main
#   workflow_dispatch:

name: Deploy (Disabled)

on:
  workflow_dispatch:

env:
  NODE_VERSION: '20'

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Generate Prisma Client
        run: npx prisma generate

      - name: Lint code
        run: npm run lint

      - name: Build application
        run: npm run build
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          DIRECT_URL: ${{ secrets.DIRECT_URL }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          SITE_URL: ${{ secrets.SITE_URL }}

      # SSH deployment step disabled until server is ready
      # - name: Deploy to Server via SSH
      #   uses: appleboy/ssh-action@v1.0.3
      #   with:
      #     host: ${{ secrets.SERVER_HOST }}
      #     username: ${{ secrets.SERVER_USER }}
      #     key: ${{ secrets.SERVER_SSH_KEY }}
      #     port: ${{ secrets.SERVER_PORT || 22 }}
      #     script: |
      #       set -e
      #       cd ${{ secrets.DEPLOY_PATH || '/var/www/iconic-website' }}
      #       git pull origin main
      #       npm ci --only=production
      #       npx prisma generate
      #       npx prisma migrate deploy
      #       npm run build
      #       pm2 restart iconic-website || pm2 start npm --name "iconic-website" -- start
      #       pm2 save

      - name: Build success
        run: echo "✅ Build completed successfully! Deploy step is disabled."
